// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Prueba 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Prueba 1', async function() {
    await driver.get("https://www.atestermate.com/AutomationExample.php")
    await driver.manage().window().setRect({ width: 1203, height: 719 })
    await driver.findElement(By.name("nEmail")).click()
    await driver.findElement(By.name("nEmail")).sendKeys("hola@test.com")
    await driver.findElement(By.id("nPassword")).click()
    await driver.findElement(By.id("nPassword")).sendKeys("12345")
    await driver.findElement(By.name("profile")).click()
    {
      const dropdown = await driver.findElement(By.name("profile"))
      await dropdown.findElement(By.xpath("//option[. = 'Automation Tester']")).click()
    }
    await driver.findElement(By.id("oneyear")).click()
    await driver.findElement(By.name("nsubmit")).click()
  })
})
